# Generated by Django 6.0 on 2025-12-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='contributors/images/')),
                ('bio', models.TextField(max_length=255)),
                ('links', models.JSONField()),
            ],
        ),
    ]
