# Generated by Django 6.0 on 2025-12-17 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagories', '0001_initial'),
        ('courses', '0001_initial'),
        ('files', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=255)),
                ('price_range', models.DecimalField(decimal_places=2, max_digits=65)),
                ('verified', models.BooleanField(default=False)),
                ('catagories', models.ManyToManyField(related_name='course_catagory', to='catagories.catagories')),
                ('courses', models.ManyToManyField(to='courses.courses')),
                ('files', models.ManyToManyField(to='files.files')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
